### ISSUE TITLE
[DDL Statements] - Quiz - Create Table with Constraints

### ISSUE THREAD

**Issue by sa4rabh** [Anupam-2105/Infosys-Springboard#1]
1) Which requirements can be implemented using a referential integrity constraint?

Ans : Customer information must be known before anything is sold to him/her 

2) Which of the following statements are TRUE? [Choose any TWO]

Ans : A Unique constraint allows multiple rows to have NULL value
Referential integrity constraint allows NULL value

3) Which requirements can be implemented using a CHECK constraint? [Choose any TWO]

Ans : Age of the customer must be greater than 21
Customer must have a residence in an Asian Country 

4) Which is the constraint that can be defined only at the column level?

Ans : NOT NULL

**Comment by Anupam-2105** [comment]
I've updated the answer. Thank you for finding the error.
